#!/usr/bin/env python3
"""Unified LLM client supporting DeepSeek, Qwen, and OpenAI providers.

Provides a common interface for OpenAI-compatible API endpoints with
built-in retry logic, token estimation, and cost calculation.

Configuration is loaded from ``.env`` via python-dotenv.  Copy
``.env.example`` to ``.env`` and fill in your API keys.  All settings
have sensible defaults so the module works even without a ``.env`` file.

Key environment variables::

    LLM_PROVIDER          - provider: deepseek (default), qwen, openai
    {PROVIDER}_API_KEY    - API key (DEEPSEEK_API_KEY, DASHSCOPE_API_KEY, OPENAI_API_KEY)
    {PROVIDER}_API_BASE   - override the default base URL
    {PROVIDER}_DEFAULT_MODEL - override the default model name
    {PROVIDER}_PRICING_INPUT  - USD per 1M input tokens
    {PROVIDER}_PRICING_OUTPUT - USD per 1M output tokens

Usage:
    from pipeline.model_client import quick_chat

    response = quick_chat("Explain what a neural network is.")
    print(response.content)
"""

import logging
import os
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional

import httpx
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

# =====================================================================
# Constants
# =====================================================================

_DEFAULT_PROVIDER = os.getenv("LLM_PROVIDER", "deepseek").lower()

_DEFAULTS: dict[str, dict] = {
    "deepseek": {
        "api_base": "https://api.deepseek.com/v1",
        "api_key_env": "DEEPSEEK_API_KEY",
        "default_model": "deepseek pro v4",
        "pricing_input": 0.27,
        "pricing_output": 1.10,
    },
    "qwen": {
        "api_base": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "default_model": "qwen-max",
        "pricing_input": 0.40,
        "pricing_output": 1.60,
    },
    "openai": {
        "api_base": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "default_model": "gpt-4o",
        "pricing_input": 2.50,
        "pricing_output": 10.00,
    },
}


def _build_config(provider_name: str, defaults: dict) -> dict:
    """Build provider config by reading from env vars, falling back to defaults.

    Looks for ``{PROVIDER}_API_BASE``, ``{PROVIDER}_DEFAULT_MODEL``,
    ``{PROVIDER}_PRICING_INPUT``, and ``{PROVIDER}_PRICING_OUTPUT`` in the
    environment.  Falls back to the hard-coded defaults when an env var is
    absent or unparseable.

    Args:
        provider_name: Lowercase provider key (``deepseek``, ``qwen``, ``openai``).
        defaults: The hard-coded fallback values.

    Returns:
        A config dict with keys ``api_base``, ``api_key_env``, ``default_model``,
        and ``pricing`` (``{input, output}``).
    """
    prefix = provider_name.upper()

    api_base = os.getenv(f"{prefix}_API_BASE", defaults["api_base"])
    default_model = os.getenv(f"{prefix}_DEFAULT_MODEL", defaults["default_model"])

    try:
        pricing_input = float(
            os.getenv(f"{prefix}_PRICING_INPUT", str(defaults["pricing_input"]))
        )
    except ValueError:
        pricing_input = defaults["pricing_input"]
    try:
        pricing_output = float(
            os.getenv(f"{prefix}_PRICING_OUTPUT", str(defaults["pricing_output"]))
        )
    except ValueError:
        pricing_output = defaults["pricing_output"]

    return {
        "api_base": api_base,
        "api_key_env": defaults["api_key_env"],
        "default_model": default_model,
        "pricing": {"input": pricing_input, "output": pricing_output},
    }


_PROVIDER_CONFIGS: dict[str, dict] = {
    name: _build_config(name, defaults)
    for name, defaults in _DEFAULTS.items()
}

MAX_RETRIES: int = 3
"""Maximum number of retry attempts for API calls."""

RETRY_BACKOFF_BASE: float = 2.0
"""Base multiplier (seconds) for exponential backoff."""

REQUEST_TIMEOUT: float = 60.0
"""HTTP request timeout in seconds."""

CHARS_PER_TOKEN_ENGLISH: int = 4
"""Approximate characters per token for alphabetic / ASCII text."""

CHARS_PER_TOKEN_CHINESE: int = 2
"""Approximate characters per token for CJK text."""

_SUPPORTED_PROVIDERS: str = ", ".join(sorted(_PROVIDER_CONFIGS.keys()))

# =====================================================================
# Data Classes
# =====================================================================


@dataclass
class Usage:
    """Token usage statistics returned from an LLM API call.

    Attributes:
        prompt_tokens: Number of tokens consumed by the input / prompt.
        completion_tokens: Number of tokens generated by the model.
        total_tokens: Sum of prompt and completion tokens.
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


@dataclass
class LLMResponse:
    """Unified response from an LLM API call.

    Attributes:
        content: The text content returned by the model.
        usage: Token usage statistics for the request.
    """

    content: str
    usage: Usage

    def __repr__(self) -> str:
        preview = self.content[:80].replace("\n", " ")
        suffix = "..." if len(self.content) > 80 else ""
        return (
            f"LLMResponse(content='{preview}{suffix}', "
            f"usage={self.usage})"
        )


# =====================================================================
# Abstract Base Class
# =====================================================================


class LLMProvider(ABC):
    """Abstract base class defining the interface for LLM providers.

    All provider implementations must subclass this and implement the
    ``chat`` method.
    """

    @abstractmethod
    def chat(self, messages: list[dict[str, str]], **kwargs) -> LLMResponse:
        """Send a chat completion request.

        Args:
            messages: A list of message dicts with ``role`` and ``content``
                keys (e.g. ``{"role": "user", "content": "Hello"}``).
            **kwargs: Additional parameters forwarded to the API
                (temperature, max_tokens, top_p, etc.).

        Returns:
            An :class:`LLMResponse` containing the model reply and token usage.

        Raises:
            httpx.HTTPError: On network or HTTP-level failures.
        """
        ...

    @property
    @abstractmethod
    def model(self) -> str:
        """Return the model identifier string used by this provider."""
        ...


# =====================================================================
# OpenAI-Compatible Provider
# =====================================================================


class OpenAICompatibleProvider(LLMProvider):
    """Generic provider for OpenAI-compatible chat completion endpoints.

    Works with any service that exposes a ``/chat/completions`` endpoint
    matching the OpenAI v1 API schema.

    Args:
        api_base: Base URL of the API (e.g. ``https://api.openai.com/v1``).
        api_key: Bearer token for authentication.
        model: Model identifier string.
    """

    def __init__(self, api_base: str, api_key: str, model: str) -> None:
        self._api_base = api_base.rstrip("/")
        self._api_key = api_key
        self._model = model

    @property
    def model(self) -> str:
        return self._model

    def chat(
        self, messages: list[dict[str, str]], **kwargs
    ) -> LLMResponse:
        """Send a chat completion request to the provider.

        Args:
            messages: A list of message dicts with ``role`` and ``content``.
            **kwargs: Additional API parameters (temperature, max_tokens, etc.).

        Returns:
            Parsed :class:`LLMResponse`.

        Raises:
            httpx.HTTPStatusError: If the server returns a non-2xx status.
            httpx.RequestError: On connection / timeout errors.
        """
        url = f"{self._api_base}/chat/completions"
        payload: dict = {
            "model": self._model,
            "messages": messages,
            **kwargs,
        }
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }

        logger.debug("POST %s with model=%s", url, self._model)
        try:
            response = httpx.post(
                url,
                json=payload,
                headers=headers,
                timeout=REQUEST_TIMEOUT,
            )
            response.raise_for_status()
        except httpx.HTTPStatusError:
            logger.error(
                "HTTP %d from %s: %s",
                response.status_code,
                self._model,
                response.text[:500],
            )
            raise
        except httpx.RequestError:
            logger.exception("Request failed for %s", self._model)
            raise

        data = response.json()
        choice = data["choices"][0]
        message = choice["message"]
        usage_raw = data.get("usage", {})

        usage = Usage(
            prompt_tokens=usage_raw.get("prompt_tokens", 0),
            completion_tokens=usage_raw.get("completion_tokens", 0),
            total_tokens=usage_raw.get("total_tokens", 0),
        )

        return LLMResponse(content=message.get("content", ""), usage=usage)


# =====================================================================
# Provider Factory
# =====================================================================


def create_provider(
    provider_name: Optional[str] = None,
    model: Optional[str] = None,
) -> OpenAICompatibleProvider:
    """Create a configured provider instance.

    Reads the API key from the appropriate environment variable and
    returns a ready-to-use :class:`OpenAICompatibleProvider`.

    Args:
        provider_name: One of ``deepseek``, ``qwen``, ``openai``.
            Defaults to the ``LLM_PROVIDER`` environment variable or
            ``deepseek``.
        model: Override the default model for the selected provider.

    Returns:
        A configured provider instance.

    Raises:
        ValueError: If the provider name is unknown or the required
            API key environment variable is not set.
    """
    name = (provider_name or _DEFAULT_PROVIDER).lower()
    if name not in _PROVIDER_CONFIGS:
        raise ValueError(
            f"Unknown provider '{name}'. "
            f"Supported: {_SUPPORTED_PROVIDERS}"
        )

    config = _PROVIDER_CONFIGS[name]
    api_key = os.getenv(config["api_key_env"])
    if not api_key:
        raise ValueError(
            f"Environment variable '{config['api_key_env']}' is not set. "
            f"Cannot authenticate with {name}."
        )

    selected_model = model or config["default_model"]
    logger.info("Creating provider '%s' with model '%s'", name, selected_model)
    return OpenAICompatibleProvider(
        api_base=config["api_base"],
        api_key=api_key,
        model=selected_model,
    )


def list_providers() -> list[str]:
    """Return a list of supported provider names."""
    return sorted(_PROVIDER_CONFIGS.keys())


def get_provider_pricing(
    provider_name: Optional[str] = None,
) -> dict[str, float]:
    """Return the per-million-token pricing dict for a provider.

    Args:
        provider_name: Provider name. Defaults to current ``LLM_PROVIDER``.

    Returns:
        Dict with ``input`` and ``output`` keys in USD per 1M tokens.
    """
    name = (provider_name or _DEFAULT_PROVIDER).lower()
    return dict(_PROVIDER_CONFIGS[name]["pricing"])


# =====================================================================
# Retry Logic
# =====================================================================


def _should_retry(status_code: int) -> bool:
    """Decide whether an HTTP response status warrants a retry.

    Retries are attempted on server errors (5xx) and rate-limiting (429).
    Client errors (4xx) other than 429 are considered permanent and are
    not retried.

    Args:
        status_code: HTTP response status code.

    Returns:
        ``True`` if the request should be retried.
    """
    return status_code >= 500 or status_code == 429


def chat_with_retry(
    messages: list[dict[str, str]],
    provider: Optional[LLMProvider] = None,
    max_retries: int = MAX_RETRIES,
    **kwargs,
) -> LLMResponse:
    """Send a chat request with automatic retry on transient failures.

    Uses exponential backoff starting from :data:`RETRY_BACKOFF_BASE`
    seconds.  Only server errors (5xx) and rate-limiting (429) are retried;
    other client errors (4xx) are raised immediately.

    Args:
        messages: A list of message dicts with ``role`` and ``content``.
        provider: An existing provider instance.  If ``None`` a default
            provider is created via :func:`create_provider`.
        max_retries: Maximum number of retries (default 3).
        **kwargs: Additional parameters forwarded to :meth:`LLMProvider.chat`.

    Returns:
        :class:`LLMResponse` from the successful call.

    Raises:
        httpx.HTTPStatusError: If all retries are exhausted or a
            non-retryable error occurs.
        httpx.RequestError: On persistent network failures.
    """
    p = provider or create_provider()
    last_error: Optional[Exception] = None

    for attempt in range(max_retries + 1):
        try:
            return p.chat(messages, **kwargs)
        except httpx.HTTPStatusError as exc:
            last_error = exc
            if not _should_retry(exc.response.status_code):
                logger.error(
                    "Non-retryable HTTP %d, not retrying.",
                    exc.response.status_code,
                )
                raise
        except httpx.RequestError as exc:
            last_error = exc

        if attempt < max_retries:
            delay = RETRY_BACKOFF_BASE ** (attempt + 1)
            logger.warning(
                "Attempt %d/%d failed: %s. Retrying in %.1fs ...",
                attempt + 1,
                max_retries + 1,
                last_error,
                delay,
            )
            time.sleep(delay)

    logger.error("All %d attempts exhausted.", max_retries + 1)
    raise last_error  # type: ignore[misc]


# =====================================================================
# Token Estimation & Cost
# =====================================================================


def estimate_tokens(text: str) -> int:
    """Estimate the number of tokens for a given text string.

    Uses a heuristic: ~4 characters per token for ASCII text and
    ~2 characters per token for CJK characters.  This is a rough
    approximation and may vary across tokenizers.

    Args:
        text: The input text to estimate.

    Returns:
        Estimated token count (minimum 1).
    """
    cjk = sum(1 for ch in text if "\u4e00" <= ch <= "\u9fff")
    ascii_chars = len(text) - cjk
    estimated = int(
        cjk / CHARS_PER_TOKEN_CHINESE + ascii_chars / CHARS_PER_TOKEN_ENGLISH
    )
    return max(estimated, 1)


def calculate_cost(
    prompt_tokens: int,
    completion_tokens: int,
    provider_name: Optional[str] = None,
) -> float:
    """Calculate the estimated USD cost of an API call.

    Uses per-million-token pricing from the provider configuration.

    Args:
        prompt_tokens: Number of input / prompt tokens.
        completion_tokens: Number of output / completion tokens.
        provider_name: Provider name.  Defaults to current ``LLM_PROVIDER``.

    Returns:
        Estimated cost in US dollars.
    """
    pricing = get_provider_pricing(provider_name)
    input_cost = (prompt_tokens / 1_000_000) * pricing["input"]
    output_cost = (completion_tokens / 1_000_000) * pricing["output"]
    return input_cost + output_cost


# =====================================================================
# Convenience Function
# =====================================================================


def quick_chat(
    prompt: str,
    system: Optional[str] = None,
    provider_name: Optional[str] = None,
    model: Optional[str] = None,
    **kwargs,
) -> LLMResponse:
    """Send a one-shot chat request – the simplest way to query an LLM.

    Constructs a message list from the given prompt and optional system
    instruction, then delegates to :func:`chat_with_retry`.

    Args:
        prompt: The user message to send.
        system: Optional system-level instruction (role ``system``).
        provider_name: Provider to use (defaults to ``LLM_PROVIDER`` env).
        model: Model override for the selected provider.
        **kwargs: Additional parameters forwarded to the chat API
            (temperature, max_tokens, etc.).

    Returns:
        :class:`LLMResponse` containing the model's reply.

    Example::

        >>> response = quick_chat("Hello, who are you?")
        >>> print(response.content)

        >>> response = quick_chat(
        ...     "Summarize this article.",
        ...     system="You are a helpful assistant.",
        ...     provider_name="openai",
        ...     temperature=0.3,
        ... )
    """
    messages: list[dict[str, str]] = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    provider = create_provider(provider_name=provider_name, model=model)
    return chat_with_retry(messages, provider=provider, **kwargs)


# =====================================================================
# Self-test (run with: python3 -m pipeline.model_client)
# =====================================================================

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    logger.info("=== Supported Providers ===")
    for p in list_providers():
        pricing = get_provider_pricing(p)
        logger.info(
            "  %s: input=$%.2f/M output=$%.2f/M",
            p,
            pricing["input"],
            pricing["output"],
        )

    logger.info("")
    logger.info("=== Token Estimation ===")
    samples = [
        "Hello, how are you?",
        "人工智能正在改变世界",
        "The quick brown fox jumps over the lazy dog. 人工智能很有趣。",
    ]
    for text in samples:
        tokens = estimate_tokens(text)
        logger.info("  '%s' -> ~%d tokens", text, tokens)

    logger.info("")
    logger.info("=== Cost Calculation (across providers) ===")
    for p in list_providers():
        cost = calculate_cost(1000, 500, provider_name=p)
        logger.info("  %s: 1000 input + 500 output -> $%.6f", p, cost)

    logger.info("")
    logger.info("=== Provider Creation ===")
    try:
        provider = create_provider()
        logger.info(
            "Default provider '%s' created with model '%s'.",
            _DEFAULT_PROVIDER,
            provider.model,
        )

        logger.info("")
        logger.info("=== Live Chat Test ===")
        response = quick_chat(
            "Reply with exactly 'OK' and nothing else.",
            provider_name=_DEFAULT_PROVIDER,
        )
        logger.info("Response: %s", response.content.strip())
        logger.info("Usage: prompt=%d completion=%d total=%d",
                     response.usage.prompt_tokens,
                     response.usage.completion_tokens,
                     response.usage.total_tokens)
    except ValueError as exc:
        logger.warning("Skipping live test: %s", exc)
    except Exception:
        logger.exception("Live test failed with unexpected error")
